# SPDX-License-Identifier: Apache-2.0

# =====================================
# * SUPPORTED I3C CORE CONFIGURATIONS *
# =====================================

default:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 32
  DctDepth: 32
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64

# TODO: AXI configuration
