# SPDX-License-Identifier: Apache-2.0

# =====================================
# * SUPPORTED I3C CORE CONFIGURATIONS *
# =====================================

ahb:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 18
  FrontendBusDataWidth: 64
  DisableInputFF: True
  ControllerSupport: False
  TargetSupport: True

ahb_ff:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 18
  FrontendBusDataWidth: 64
  DisableInputFF: False
  ControllerSupport: False
  TargetSupport: True

axi:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: True
  NumPrivIds: 4
  DisableInputFF: True
  ControllerSupport: False
  TargetSupport: True

axi_ff:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: True
  NumPrivIds: 4
  DisableInputFF: False
  ControllerSupport: False
  TargetSupport: True
